#############################################################################
#####									#####
#####         GGGGGGGG	  MM      MM     DDDDDDD    BBBBBBB 		#####
#####        GG      	  M M    M M     D     DD   B      B   		#####
#####       GG    GGG	  M  M  M  M     D      D   BBBBBBB    		#####
#####        GG     GG	  M   MM   M     D     DD   B      B   		#####
#####         GGGGGGG	  M        M     DDDDDDD    BBBBBBB    		#####
#####  			      	 CREW					#####
#############################################################################
# Copyright (C) 2007-2009 GMDB <http://sourceforge.net/projects/gm-db>      #
#									    #
# This program is free software: you can redistribute it and/or modify      #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.					    #
#									    #
# This program is distributed in the hope that it will be useful,	    #
# but WITHOUT ANY WARRANTY; without even the implied warranty of	    #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the		    #
# GNU General Public License for more details.				    #
#									    #
# You should have received a copy of the GNU General Public License	    #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.     #
#############################################################################




#####	command	#####

SET NAMES 'utf8';

UPDATE `command` SET `help`='Syntax: .account\r\n\r\nZeigt die Berechtigungsstufe Ihres Accounts an.' WHERE (`name`='account');
UPDATE `command` SET `help`='Syntax: .account create $account $password\r\n\r\nErstellt einen Account mit angegebenem Passwort.' WHERE (`name`='account create');
UPDATE `command` SET `help`='Syntax: .account delete $account\r\n\r\nLöscht Account mit allen Charakteren.' WHERE (`name`='account delete');
UPDATE `command` SET `help`='Syntax: .account onlinelist\r\n\r\nZeigt eine Liste aller zurzeit verwendeter Acccounts.' WHERE (`name`='account onlinelist');
UPDATE `command` SET `help`='Syntax: .account set addon [$account] #addon\r\n\r\nErlaubt dem angegebenen Benutzer(möglicherweise dem ausgewählten Charakter) die Erweiterungen. Mögliche Werte: 0 - normal, 1 - tbc, 2 - wotlk.' WHERE (`name`='account set addon');
UPDATE `command` SET `help`='Syntax: .account set gmlevel [$account] #level\r\n\r\nSetzt Zugriffsberechtigung des ausgewählten Spielers (kann nicht auf sich selbst angewendet werden) oder für Account $name zum Level #level.\r\n\r\n#Das Level kann von 0 bis 3 reichen.' WHERE (`name`='account set gmlevel');
UPDATE `command` SET `help`='Syntax: .account set password $account $password $password\r\n\r\nSetzt Passwort für angegebenen Account.' WHERE (`name`='account set password');
UPDATE `command` SET `help`='Syntax: .additem #itemid/[#itemname]/#shift-click-item-link #itemcount\r\n\r\nFügt die festgelegte Anzahl von Items der id #itemid (oder exakter (!) Name $itemname in Klammern, oder mit shift-click generiertem Link eines Items aus dem Inventar oder Rezept) zu Ihrem oder dem Inventar, des ausgewählten Charakters. Bleibt #itemcount leer, so wird nur ein Item hinzugefügt.\r\n.' WHERE (`name`='additem');
UPDATE `command` SET `help`='Syntax: .additemset #itemsetid\r\n\r\nFügt Items eines Itemsets der id #itemsetid zu Ihrem oder dem Inventar, des ausgewählten Charakters, hinzu. Jedes Teil des Itemsets wird einmal hinzugefügt.' WHERE (`name`='additemset');
UPDATE `command` SET `help`='Syntax: .addmove #creature_guid [#waittime]\r\n\r\nFügt die aktuelle Position als Waypoint für die creature mit der guid #creature_guid hinzu. Optional kann eine Wartezeit für diesen Punkt angegeben werden.' WHERE (`name`='addmove');
UPDATE `command` SET `help`='Syntax: .announce $MessageToBroadcast\r\n\r\nSendet eine Systemnachricht an alle Spieler in das Chatfenster.' WHERE (`name`='announce');
UPDATE `command` SET `help`='Syntax: .aura #spellid\r\n\r\nFügt die Aura vom dem Spell #spellid der angewählten Einheit hinzu.' WHERE (`name`='aura');
UPDATE `command` SET `help`='Syntax: .ban account $Name $bantime $reason\r\nBan account kicked den Spieler ebensfalls.\r\n$bantime: Eine negative Zahl bewirkt einen permanenten Bann, anderenfalls verwende ein Format wie "4d20h3s".' WHERE (`name`='ban account');
UPDATE `command` SET `help`='Syntax: .ban character $Name $bantime $reason\r\nBan account and kick player.\r\n$bantime: Eine negaive Zahl bewirkt einen permanenten Bann, anderenfalls verwende ein Format wie "4d20h3s".' WHERE (`name`='ban character');
UPDATE `command` SET `help`='Syntax: .ban ip $Ip $bantime $reason\r\nBan IP.\r\n$bantime: Eine negaive Zahl bewirkt einen permanenten Bann, anderenfalls verwende ein Format wie "4d20h3s".' WHERE (`name`='ban ip');
UPDATE `command` SET `help`='Syntax: .baninfo account\r\nZeigt Euch die vollen Informationen über einen speziellen Bann an.' WHERE (`name`='baninfo account');
UPDATE `command` SET `help`='Syntax: .baninfo character\r\nZeigt Euch die vollen Informationen über einen speziellen Bann an.' WHERE (`name`='baninfo character');
UPDATE `command` SET `help`='Syntax: .baninfo ip\r\nZeigt Euch die vollen Informationen über einen speziellen Bann an.' WHERE (`name`='baninfo ip');
UPDATE `command` SET `help`='Syntax: .bank\r\n\r\nÖffnet Ihr Bankschliessfach.' WHERE (`name`='bank');
UPDATE `command` SET `help`='Syntax: .banlist account [$Name]\r\nSucht in der Bannliste nach einem Account Namen mit einem bestimmten Muster oder zeigt alle gebannten Accounts.' WHERE (`name`='banlist account');
UPDATE `command` SET `help`='Syntax: .banlist character $Name\r\nSucht in der Bannliste nach einem Charakter Namen mit einem bestimmten Muster. Angabe eines Musters benötigt.' WHERE (`name`='banlist character');
UPDATE `command` SET `help`='Syntax: .banlist ip [$Ip]\r\nSucht in der Bannliste nach einer IP mit einem einem bestimmten Muster oder zeigt alle gebannten IPs.' WHERE (`name`='banlist ip');
UPDATE `command` SET `help`='Syntax: .cast #spellid [triggered]\r\n  #spellid wird auf das angewählte Ziel ausgeführt. Falls kein Ziel angewählt ist, wird der Zauber auf euch ausgeführt. Falls ''triggered'' oder ein Teil davon angegeben wurde, wird der Zauber mit einer triggered flag ausgeführt.' WHERE (`name`='cast');
UPDATE `command` SET `help`='Syntax: .cast back #spellid [triggered]\r\n  Das angewählte Ziel führt den Zauber #spellid auf euren Charakter aus. Falls ''triggered'' oder ein Teil davon angegeben wurde, wird der Zauber mit einer triggered flag ausgeführt.' WHERE (`name`='cast back');
UPDATE `command` SET `help`='Syntax: .cast dist #spellid [#dist [triggered]]\r\n  Ihr werdet den Zauber auf einen Punkt in der Distanz #dist wirken. Falls ''trigered'' oder nur ein Teil angegeben wurde, dann wird der Zauber mit triggered flag gewirkt. Nicht alle Zauber können als Distanzzauber gewirkt werden.' WHERE (`name`='cast dist');
UPDATE `command` SET `help`='Syntax: .cast self #spellid [triggered]\r\nFührt #spellid von Ziel auf das Ziel selbst aus. Falls ''triggered'' oder ein Teil davon angegeben wurde, wird der Zauber mit einer triggered flag ausgeführt.' WHERE (`name`='cast self');
UPDATE `command` SET `help`='Syntax: .cast target #spellid [triggered]\r\n  Das angewählte Ziel führt den Zauber #spellid auf sein Ziel aus. Falls ''triggered'' oder ein Teil davon angegeben wurde, wird der Zauber mit einer triggered flag ausgeführt.' WHERE (`name`='cast target');
UPDATE `command` SET `help`='Syntax: .chardelete $charactername\r\n\r\nLöscht angegebenen Charakter.' WHERE (`name`='chardelete');
UPDATE `command` SET `help`='Syntax: .combatstop [$playername]\r\nHält den Nahkampf des angewählten Charakters an. Falls kein Spieler angewählt ist, wird der Befehl auf Euch gewirkt. Falls $playername angegeben wurde, dann wird der Befehl auf den Onlinespieler $playername gewirkt.' WHERE (`name`='combatstop');
UPDATE `command` SET `help`='Syntax: .commands\r\n\r\nZeigt die Befehle Ihrer Berechtigungsstufe an.' WHERE (`name`='commands');
UPDATE `command` SET `help`='Syntax: .cooldown [#spell_id]\r\n\r\nEntfernt alle (wenn spell_id nicht angebeben) oder nur den Cooldown von #spell_id vom ausgewählten Charakter oder von Ihnen (wenn niemand ausgewählt).' WHERE (`name`='cooldown');
UPDATE `command` SET `help`='Syntax: .damage $damage_amount [$school [$spellid]]\r\n\r\nFügt dem Ziel $damage zu. Falls $school und $spellid nicht angegeben wurde, dann wird normaler Melee Damage ohne irgendwelche Modifikationen ausgeführt. Falls $school angegeben wurde wird der Schaden mit Rüstungsreduzierung modifiziert (falls school physikal ist), und das Ziel wird die Modifikation absorbieren und das Ergebnis als Melee Damager auf das Ziel gewirkt. Falls spell angegeben wurde wird der Schaden mofiziert und als Zauberschaden gewirkt. $spellid kann als Shift-Link verwendet werden.' WHERE (`name`='damage');
UPDATE `command` SET `help`='Syntax: .debug anim #emoteid\r\n\r\nSpielt die Animation #emoteid für Ihren Charakter ab.' WHERE (`name`='debug anim');
UPDATE `command` SET `help`='Syntax: .debug arena\r\n\r\nSchaltet um auf Debug Mode für Arenen. Im Debug Mode kann der GM eine Arena mit einem einzigen Spieler starten.' WHERE (`name`='debug arena');
UPDATE `command` SET `help`='Syntax: .debug bg\r\n\r\nSchaltet um auf Debug Mode für Schlachtfelder. Im Debug Mode kann der GM ein Schlachtfeld mit einem einzigen Spieler starten.' WHERE (`name`='debug bg');
UPDATE `command` SET `help`='Syntax: .debug getvalue #field #isInt\r\n\r\nGibt das Feld #field der ausgewählten Kreatur aus. Wenn keine Kreatur angewählt ist, gibt er den Wert Eures Feldes aus.\r\n\r\nBenutze einen #isInt mit dem Wert 1, wenn es sich beim gesuchte Feld um einen Intergerwert handelt.' WHERE (`name`='debug getvalue');
UPDATE `command` SET `help`='Syntax: .debug playsound #soundid\r\n\r\nSpielt die Musik mit #soundid.\r\nDie Musik wird nur für Euch gespielt werden. Andere Spieler werden dies nicht hören.\r\nVorsicht: Der Client hat warscheinlich mehr als 5000 Musikstücke...' WHERE (`name`='debug playsound');
UPDATE `command` SET `help`='Syntax: .debug setvalue #field #value #isInt\r\n\r\nSetzt das Feld #field der angewählten Kreatur mit dem Wert #value. Falls keine Kreatur angewählt ist, wird der Inhalt Eures Feldes gestzt.\r\n\r\nBenutze einen #isInt Wert 1, falls #value ein Integer ist.' WHERE (`name`='debug setvalue');
UPDATE `command` SET `help`='Syntax: .debug standstate #emoteid\r\n\r\nÄndert den Emote Eures Charakters während er steht nach #emoteid.' WHERE (`name`='debug standstate');
UPDATE `command` SET `help`='Syntax: .debug update #field #value\r\n\r\nAktualisiert das Feld #field des angewählten Charakters oder der angewählten Kreatur auf den Wert #value.\r\n\r\nFalls kein #value angegeben wurde, wird der Inhalt des Feldes #field angezeigt.' WHERE (`name`='debug update');
UPDATE `command` SET `help`='Syntax: .delticket all\r\n        .delticket #num\r\n        .delticket $character_name\r\n\rall löscht alle Tickets vom Server, $character_name löscht alle Tickets von diesm Charakter, #num löscht das Ticket mit der Nummer #num.' WHERE (`name`='delticket');
UPDATE `command` SET `help`='Syntax: .demorph\r\n\r\nGibt dem angewählten Spieler sein ursprüngliches Aussehen wieder.' WHERE (`name`='demorph');
UPDATE `command` SET `help`='Syntax: .die\r\n\r\nTötet den ausgewählten Spieler. Wenn kein Spieler ausgewählt ist, wird der Befehl Euch töten.' WHERE (`name`='die');
UPDATE `command` SET `help`='Syntax: .dismount\r\n\r\nMounted Euch ab, falls Ihr aufgemounted seid.' WHERE (`name`='dismount');
UPDATE `command` SET `help`='Syntax: .distance [$name/$link]\r\n\r\nZeigt den Abstand von Eurem Charakter zu der angewählten Kreatur/dem angewählten Spieler, oder dem Spieler mit dem Namen $name, oder dem Spieler/der Kreatur/dem Gameobject auf den/die/das mit einem Shift-Link mit guid verwiesen wurde, an.' WHERE (`name`='distance');
UPDATE `command` SET `help`='Syntax: .event #event_id\r\nZeigt die Details des Events mit #event_id.' WHERE (`name`='event');
UPDATE `command` SET `help`='Syntax: .event activelist\r\nZeigt eine Liste mit den derzeitig aktiven Events an.' WHERE (`name`='event activelist');
UPDATE `command` SET `help`='Syntax: .event start #event_id\r\nStartet das Event #event_id. Setzt die Startzeit des Events auf den jetzigen Moment (die Änderung wird nicht in der DB gespeichert).' WHERE (`name`='event start');
UPDATE `command` SET `help`='Syntax: .event stop #event_id\r\nStoppt das Event #event_id. Setzt die Startzeit des Events auf eine Zeit in der Vergangenheit, so ist der jetzige Moment die Endzeit des Events (die Änderung wird nicht in der DB gespeichert).' WHERE (`name`='event stop');
UPDATE `command` SET `help`='Syntax: .explorecheat #flag\r\n\r\nDeckt alle Karten für den ausgewählten Spieler auf oder versteckt sie für Ihn. Wenn kein Spieler angewählt ist, versteckt oder deckt er alle Karten für euch auf.\r\n\r\nBenutzt einen Wert von 1 für #flag um alle Karten aufzudecken, benutzt einen Wert von 0 für #flag um sie zu verstecken.' WHERE (`name`='explorecheat');
UPDATE `command` SET `help`='Syntax: .flusharenapoints\r\n\r\nBenutze dies, um die Arenapunkte, basierend auf den Arenateamwertungen, zu verteilen, und eine neue Woche zu starten.' WHERE (`name`='flusharenapoints');
UPDATE `command` SET `help`='Syntax: .gm [on/off]\r\n\r\nAktiviert oder Deaktiviert im Spiel den GM-Modus oder zeigt den derzeitigen Status (On/Off).' WHERE (`name`='gm');
UPDATE `command` SET `help`='Syntax: .gm chat [on/off]\r\n\r\nAktiviert oder Deaktiviert den Chat GM-Modus (zeigt das GM-Zeichen in den Nachrichten) oder zeigt den derzeitigen Status (On/Off).' WHERE (`name`='gm chat');
UPDATE `command` SET `help`='Syntax: .gm fly [on/off]\r\nAktiviert/Deaktiviert den GM Flugmodus.' WHERE (`name`='gm fly');
UPDATE `command` SET `help`='Syntax: .gm list\r\n\r\nZeigt eine Liste aller Gamemaster und Zugriffsberechtigungen an.' WHERE (`name`='gm list');
UPDATE `command` SET `help`='Syntax: .gm on/off\r\n\r\nAktiviert oder deaktiviert den GM MODUS' WHERE (`name`='gm');
UPDATE `command` SET `help`='Syntax: .gm ingame\r\n\r\nZeigt alle verfügbaren Gamemaster an.' WHERE (`name`='gm ingame');
UPDATE `command` SET `help`='Syntax: .gm visible on/off\r\n\r\nGibt den zerzeitgen Sichtbarkeitsstatus an oder macht den GM sichtbar(on) oder unsichtbar(off) für andere Spieler.' WHERE (`name`='gm visible');
UPDATE `command` SET `help`='Syntax: .goname $charactername\r\n\r\nTeleportiert Euch zu dem eingegebenen Spieler. Entweder Ihr gebt den Charakternamen genau an oder Ihr klickt auf das Porträt des Charakters, z.B. wenn Ihr in einer Gruppe seid.' WHERE (`name`='goname');
UPDATE `command` SET `help`='Syntax: .go creature #creature_guid\r\nTeleportiert Euren Charakter zu der Kreatur mit guid #creature_guid.\r\n.gocreature #creature_name\r\nTeleportiert euren Charakter zu der Kreatur mit diesem Namen.\r\n.gocreature id #creature_id\r\nTeleportiert Euren Charakter zu einer Kreatur, die vom template mit diesem entry gespawnt wurde.\r\n*Wenn* mehr als eine Kreatur gefunden werden, so werdet Ihr zur ersten, die in der Datenbank gefunden wird, teleportiert.' WHERE (`name`='go creature');
UPDATE `command` SET `help`='Syntax: .go graveyard #graveyardId\r\n Teleportiert zu dem Friedhof mit der angegebenen graveyardId.' WHERE (`name`='go graveyard');
UPDATE `command` SET `help`='Syntax: .go grid #gridX #gridY [#mapId]\r\n\r\nTeleportiert den GM in das Zentrum des grid mit den angegebenen Indizes auf der Karte #mapId (oder auf die derzeitige Karte, falls keine angegeben wurde).' WHERE (`name`='go grid');
UPDATE `command` SET `help`='Syntax: .go object #object_guid\r\nTeleportiert Euren Charakter zu dem Gameobject mit der guid #object_guid' WHERE (`name`='go object');
UPDATE `command` SET `help`='Syntax: .go trigger #trigger_id\r\n\r\nTeleportiert Euren Charakter zu der Areatrigger mit der ID #trigger_id. Der Charakter wird zum Ziel des Triggers teleportiert werden, falls der außgewählte Areatrigger ein Teleporttrigger ist.' WHERE (`name`='go trigger');
UPDATE `command` SET `help`='Syntax: .go xy #x #y [#mapid]\r\n\r\nTeleportiert den Spieler zu dem Punkt mit den Koordinaten (#x,#y) auf den Boden (oder ins Wasser) der Karte #mapid oder auf dieselbe Karte, wenn #mapid nicht angegeben wurde.' WHERE (`name`='go xy');
UPDATE `command` SET `help`='Syntax: .go xyz #x #y #z [#mapid]\r\n\r\nTeleportiert den Spieler zu dem Punkt mit den Koordinaten (#x,#y,#z) auf den Boden (oder ins Wasser) der Karte #mapid oder auf die derzeitige Karte, wenn #mapid nicht angegeben wurde.' WHERE (`name`='go xyz');
UPDATE `command` SET `help`='Syntax: .go zonexy #x #y [#zone]\r\n\r\nTeleportiert den Spieler zu dem Punkt mit den Client-Koordinaten (#x,#y) auf den Boden (oder ins Wasser) der Karte #zoneid oder auf die derzeitige Karte, wenn #zoneid nicht angegeben wurde. Ihr könnt mit dem Befehl .lookup area $namepart die Zone suchen.' WHERE (`name`='go zonexy');
UPDATE `command` SET `help`='Syntax: .gobject add #id <spawntimeSecs>\r\n\r\nFügt ein Gameobject aus gameobject_template in die Welt an Eure derzeitige Position ein, indem Ihr #id verwendet.\r\nspawntimesecs setzt die Spawnzeit, diese Angabe ist optional.\r\n\r\nHinweis: Dies ist eine Kopie von .gameobject.' WHERE (`name`='gobject add');
UPDATE `command` SET `help`='Syntax: .gobject delete #go_guid\r\nEntfernt das Gameobject mit der guid #go_guid.' WHERE (`name`='gobject delete');
UPDATE `command` SET `help`='Syntax: .gobject move #goguid [#x #y #z]\r\n\r\nBewegt das Gameobject #goguid auf die Koordinaten des Charakters (oder auf die Koordinaten (#x,#y,#z), falls diese angegeben wurden).' WHERE (`name`='gobject move');
UPDATE `command` SET `help`='Syntax: .gobject near  [#distance]\r\n\r\nZeigt Gameobjects, die sich in der Distanz #distanz vom Spieler befinden. Zeigt Gameobjects guids und Koordinaten sortiert nach der Distanz vom Charakter an. Falls #distance nicht angegeben wurde, so wird 10 als Standardwert benutzt.' WHERE (`name`='gobject near'); 
UPDATE `command` SET `help`='Syntax: .gobject phase #guid #phasemask\r\n\r\nDie Phasemask des Gameobjects mit der DB guid #guid wird auf #phasemask geändert zusammen mit einem Update für die dazugehörende Weltansicht für die Spieler. Der Gameobjectstatus wird in der DB gespeichert und ist dauerhaft.' WHERE (`name`='gobject phase');
UPDATE `command` SET `help`='Syntax: .gobject turn #goguid \r\n\r\nSetzt für das Gameobject #goguid die Blickrichtung genauso wie Euer Charakter derzeit blickt.' WHERE (`name`='gobject turn');
UPDATE `command` SET `help`='Syntax: .gobject target [#go_id|#go_name_part]\r\n\r\nSpürt das nächstgelegene Gameobject auf und zeige seine Position an. Falls #go_id oder #go_name_part angegeben wurde, so wird das nächstgelegene Gameobject mit gamobject_template id #go_id oder mit dem angegebenen Teil des Namens #go_name aufgespürt und angezeigt.' WHERE (`name`='gobject target');
UPDATE `command` SET `help`='Syntax: .gps [$name|$shift-link]\r\n\r\nZeigt die Positioninfo für den ausgewählten Charakter oder für die ausgewählte Kreatur an (ebenso wird dies für eine Spieler angegeben wenn der Name $name angegeben wurde, oder für eine Kreatur/ein Gameobject wenn der Shift-Link einer Kreatur/eines Gameobject angegeben wurde). Die Positioninfo beinhaltet X, Y, Z, Ausrichtung, map Id und zone Id' WHERE (`name`='gps');
UPDATE `command` SET `help`='Syntax: .groupgo $charactername\r\n\r\nTeleportiert den Zielcharakter und seine Gruppe zu Euch.' WHERE (`name`='groupgo');
UPDATE `command` SET `help`='Syntax: .guid\r\n\r\nZeigt die GUID des ausgewählten Charakters an.' WHERE (`name`='guid');
UPDATE `command` SET `help`='Syntax: .guild create $GuildLeaderName $GuildName\r\n\r\nErstellt eine Gilde mit dem Namen $GuildName mit dem Spieler $GuildLeaderName als Gildenleiter.' WHERE (`name`='guild create');
UPDATE `command` SET `help`='Syntax: .guild delete $GuildName\r\n\r\nLöscht die Gilde mit dem Namen $GuildName.' WHERE (`name`='guild delete');
UPDATE `command` SET `help`='Syntax: .guild invite $CharacterName $GuildName\r\n\r\nFügt den Spieler $CharacterName der Gilde $GuildName hinzu.' WHERE (`name`='guild invite');
UPDATE `command` SET `help`='Syntax: .guild rank $CharacterName #Rank\r\n\r\nDer Spieler $CharacterName erhält den Rang #Rank in der Gilde.' WHERE (`name`='guild rank');
UPDATE `command` SET `help`='Syntax: .guild uninvite $CharacterName\r\n\r\nEntfernt den Spieler $CharacterName von der Gilde.' WHERE (`name`='guild uninvite');
UPDATE `command` SET `help`='Syntax: .help [$command]\r\n\r\nZeigt die Anwendungsinformationen für den eingegebenen $command an. Falls kein $command angegeben wurde werden alle verfügbaren Befehle angezeigt' WHERE (`name`='help');
UPDATE `command` SET `help`='Syntax: .hidearea #areaid\r\n\r\nVersteckt die Region von #areaid für den ausgewählten Charakter. Wenn kein Charakter angewählt ist, wird diese Region für dich ausgeblendet.' WHERE (`name`='hidearea');
UPDATE `command` SET `help`='Syntax: .honor add $amount\r\n\r\nFügt eine bestimmte Anzahl von Ehre (heute bekommen) dem angewählten Spieler hinzu.' WHERE (`name`='honor add');
UPDATE `command` SET `help`='Syntax: .honor addkill\r\n\r\nFügt die angewählte Einheit als eine von Euren heutigen PvP-Kills hinzu (Ihr bekommt nur Ehre falls diese Einheit ein Rassenoberhaupt ode rein Spieler ist)' WHERE (`name`='honor addkill');
UPDATE `command` SET `help`='Syntax: .honor update\r\n\r\nZwingt des gestrige Ehrenfeld mit den heutigen Daten erneuert zu werden, die heutigen Daten werden für den angewählten Spieler gelöscht werden.' WHERE (`name`='honor update');
UPDATE `command` SET `help`='Syntax: .hover #flag\r\n\r\nAktiviert oder deaktiviert den Schwebezustand für Euren Charakter.\r\n\r\nBenutze einen Wert von 1 für #flag zum aktivieren des Schwebens, benutze einen Wert von 0 für #flag zum deaktivieren.' WHERE (`name`='hover');
UPDATE `command` SET `help`='Syntax: .instance unbind all\r\n  Alle Verbindungen des angewählten Spieler werden gelöscht.' WHERE (`name`='instance unbind');
UPDATE `command` SET `help`='Syntax: .instance listbinds\r\n  Listet die Verbindungen des angewählten Spielers auf.' WHERE (`name`='instance listbinds');
UPDATE `command` SET `help`='Syntax: .instance stats\r\n  Zeigt die Statistiken der Instanzen an.' WHERE (`name`='instance stats');
UPDATE `command` SET `help`='Syntax: .instance savedata\r\n  Speichert die InstanceData für die Karte des derzeitigen Spielers in der DB.' WHERE (`name`='instance savedata');
UPDATE `command` SET `help`='Syntax: .itemmove #sourceslotid #destinationslotid\r\n\r\nBewegt ein Item vom Slot #sourceslotid zum Slot #destinationslotid in Ihrem Inventar.\r\n\r\nNoch nicht hinzugefügt.' WHERE (`name`='itemmove');
UPDATE `command` SET `help`='Syntax: .kick [$charactername]\r\n\r\nKickt den eigegebenen Charakternamen von der Welt. Falls kein Charaktername eingegeben wurde, wird der angewählte Spieler (außer dir selbst) gekickt.' WHERE (`name`='kick');
UPDATE `command` SET `help`='Syntax: .learn #spell [all]\r\n\r\nDer angewählte Charakter lernt den Zauber (Spell) mit der id #spell. Wenn ''all'' angegeben wird, werden alle Ränge erlernt.' WHERE (`name`='learn');
UPDATE `command` SET `help`='Syntax: .learn all\r\n\r\nLernt alle großen, unterschiedlichen Zauber (Spells), dies könnte für einen Administrator nützlich sein.' WHERE (`name`='learn all');
UPDATE `command` SET `help`='Syntax: .learn all_default [$playername]\r\n\r\nLernt für den ausgewählten/$playername Spieler alle Standardzauber seiner Rasse/Klasse und Zauber, die er durch abgeschlossenen Quests bekam.' WHERE (`name`='learn all_default');
UPDATE `command` SET `help`='Syntax: .learn all_gm\r\n\r\nLernt alle vorgegebenen Zauber (Spells) für einen Gamemaster.' WHERE (`name`='learn all_gm');
UPDATE `command` SET `help`='Syntax: .learn all_lang\r\n\r\nLernt alle Sprachen.' WHERE (`name`='learn all_lang');
UPDATE `command` SET `help`='Syntax: .learn all_myclass\r\n\r\nLernt alle Zauber (Spells) und Talente, die für die Klasse verfügbar sind.' WHERE (`name`='learn all_myclass');
UPDATE `command` SET `help`='Syntax: .learn all_myspells\r\n\r\nLernt alle Zauber (Spells) (ausgenommen der Talente und der Zauber bei denen der ersten Rang von Talenten erlernt wird), die für die Klasse verfügbar sind.' WHERE (`name`='learn all_myspells');
UPDATE `command` SET `help`='Syntax: .learn all_mytalents\r\n\r\nLernt alle Talente (und Zauber bei denen der erste Rang von Talenten erlernt wird), die für die Klasse verfügbar sind.' WHERE (`name`='learn all_mytalents');
UPDATE `command` SET `help`='Syntax: .learn all_recipes [$profession]\r\rLehrt Euch alle Rezepte eines speziellen Berufes und setzt die Fähigkeit auf das Maximum.\rBeispiel: .learn all_recipes enchanting' WHERE (`name`='learn all_recipes');
UPDATE `command` SET `help`='Syntax: .learn crafts\r\n\r\nlernt alle Berufe und Rezepte.' WHERE (`name`='learn all_crafts');
UPDATE `command` SET `help`='Syntax: .levelup [$playername] [#numberoflevels]\r\n\r\nErhöht/Senkt das Level des Spielers mit $playername (oder des angewählten Spielers wenn kein Name angegeben wurde) um #numberoflevels oder +1, falls kein #numberoflevels angegeben wurde). Falls #numberoflevels nicht ausgelassen wurde, wird das Level um 1 erhöht. Falls #numberoflevels 0 ist, wird das selbe Level von neuem begonnen. Falls kein Charakter angewählt wurde und kein Name angegeben wurde, wird Euer Level verändert. Der Befehl kann bei Charakteren verwendet werden die offline sind. Alle Statistiken und Attribute werden neu ermittelt. Wenn das Level heruntergesetzt wurde können die Talente resetet werden. Ebenso können angelegte Items mit einem niedrigeren Level verlohren gehen, wenn das Level heruntergesetzt wird.' WHERE (`name`='levelup');
UPDATE `command` SET `help`='Syntax: .linkgrave #graveyard_id [alliance|horde]\r\n\r\nSetzt den derzeitigen Bereich als Friedhofsregion für alle (oder für [alliance|horde]). Somit werden Charaktergeister immer zum nächstliegenden Friedhof gebracht nachdem sie gestorben sind, falls der Friedhof der nächste ist und den Geist dieser Fraktion akzeptiert. Füge nur einen einzelnen Friedhof zu einer anderen Karte hinzu und nur wenn kein Friedhof verlingt ist.' WHERE (`name`='linkgrave');
UPDATE `command` SET `help`='Syntax: .list creature #creature_id [#max_count]\r\n\r\nZeigt Kreaturen mit der ID #creature_id, die in der Welt gefunden wurden. Zeigt die guids der Kreatur und die Koordianten an, diese werden nach der Distanz zum Charakter aufgelistet. Es werden maximal #max_count ausgegeben. Falls #max_count nicht angegeben wurde wird der Wert 10 als Standartwert benutzt.' WHERE (`name`='list creature');
UPDATE `command` SET `help`='Syntax: .list item #item_id [#max_count]\r\n\r\nZeigt die Items mit der ID #item_id, die im Inventar, der Post, den Auktionen oder den Gilden aller Spieler gefunden wurden. Zeigt die Itemguids, Besitzerguids der Items, Besitzeraccount und Besitzername (Gildenname and Guid falls Gildenbank) an. Gibt maximal #max_count Items aus. Wenn #max_count nicht angegeben wurde wir 10 als Standartwert benutzt.' WHERE (`name`='list item');
UPDATE `command` SET `help`='Syntax: .list object #gameobject_id [#max_count]\r\n\r\nZeigt Gameobjects mit der ID #gameobject_id, die in der Welt gefunden wurden an. Zeigt die Gameobjects mit guids und Koordinaten an, sortiert nach der Distanz zum Charakter. Gibt maximal #max_count Gameobjects aus. Wenn #max_count nicht angegeben wurde wir 10 als Standartwert benutzt.' WHERE (`name`='list object');
UPDATE `command` SET `help`='Syntax: .loadscripts $scriptlibraryname\r\n\r\nEntlädt die derzeitige und lädt die Scriptlibrary $scriptlibraryname oder lädt die aktuelle erneut, falls $scriptlibraryname nicht angegeben ist, für den Fall das Ihr sie verändert habt während der Server lief.' WHERE (`name`='loadscripts');
UPDATE `command` SET `help`='Syntax: .lockaccount [on|off]\r\n\r\nErlaubt den Login für den Account nur mit der derzeitig gebrauchten IP oder wiederruft diesen Befehl.' WHERE (`name`='lockaccount');
UPDATE `command` SET `help`='Syntax: .lookup area $namepart\r\n\r\nSucht nach einem Gebiet mit $namepart, und gibt alle gefundenen Ergebnisse mit deren area IDs aus.' WHERE (`name`='lookup area');
UPDATE `command` SET `help`='Syntax: .lookup creature $namepart\r\n\r\nSucht nach einer Kreatur mit $namepart, und gibt alle gefundenen mit ihrer Kreaturen ID aus.' WHERE (`name`='lookup creature');
UPDATE `command` SET `help`='Syntax: .lookup event $name\r\nVersucht die ID des Events mit dem angegebenen Namen $name zu finden.' WHERE (`name`='lookup event');
UPDATE `command` SET `help`='Syntax: .lookup faction $name\r\nVersucht die ID von der Fraktion mit dem angegebenen Namen $name zu finden.' WHERE (`name`='lookup faction');
UPDATE `command` SET `help`='Syntax: .lookup item $itemname\r\n\r\nSucht nach einem Item mit $itemname, und gibt alle gefundenen mit ihrer Item ID aus.' WHERE (`name`='lookup item');
UPDATE `command` SET `help`='Syntax: .lookup itemset $itemname\r\n\r\nSucht nach einem Itemset mit $namepart, und gibt alle gefundenen mit ihrer Item ID aus.' WHERE (`name`='lookup itemset');
UPDATE `command` SET `help`='Syntax: .lookup object $objname\r\n\r\nSucht nach einem Gameobject mit $namepart, und gibt alle gefundenen mit ihrer Gameobject ID aus.' WHERE (`name`='lookup object');
UPDATE `command` SET `help`='Syntax: .lookup player account $account ($limit) \r\n\r\n Sucht Spieler, deren angegebener Accountname $account ist. Mit dem optionalen Parameter $limit kann die Anzahl der Ergebnisse begrenzt werden.' WHERE (`name`='lookup player account');
UPDATE `command` SET `help`='Syntax: .lookup player ip $ip ($limit) \r\n\r\n Sucht Spieler, deren Account ast_ip $ip ist. Mit dem optionalen Parameter $limit kann die Anzahl der Ergebnisse begrenzt werden.' WHERE (`name`='lookup player ip');
UPDATE `command` SET `help`='Syntax: .lookup player email $email ($limit) \r\n\r\n Sucht Spieler, deren angegebene Accountemail $email ist. Mit dem optionalen Parameter $limit kann die Anzahl der Ergebnisse begrenzt werden.' WHERE (`name`='lookup player email');
UPDATE `command` SET `help`='Syntax: .lookup quest $namepart\r\n\r\nSucht nach einem Quest mit $namepart, und gibt alle gefundenen mit ihrer Quest ID aus.' WHERE (`name`='lookup quest');
UPDATE `command` SET `help`='Syntax: .lookup skill $namepart\r\n\r\nSucht nach einem Skill mit $namepart, und gibt alle gefundenen mit ihrer Skill ID aus.' WHERE (`name`='lookup skill');
UPDATE `command` SET `help`='Syntax: .lookup spell $namepart\r\n\r\nSucht nach einen Zauber (Spell) mit $namepart, und gibt alle gefundenen mit ihrere Spell ID aus.' WHERE (`name`='lookup spell');
UPDATE `command` SET `help`='Syntax: .lookup tele $substring\r\n\r\nSucht und gibt alle .tele Gebiete, die $substring im Namen haben, aus.' WHERE (`name`='lookup tele');
UPDATE `command` SET `help`='Syntax: .maxskill\r\nSetzt alle Skills des angewählten Spielers auf ihren maxiamlen Wert für dessen derzeitiges Level.' WHERE (`name`='maxskill');
UPDATE `command` SET `help`='Syntax: .Mod32Value #field #value\r\n\r\nFügt #value in das Feld #field Eures Charakters hinzu.' WHERE (`name`='Mod32Value');
UPDATE `command` SET `help`='Syntax: .modify arena #value\r\nFügt die Anzahl $amount an Arenapunkten dem angewählten Spieler hinzu.' WHERE (`name`='modify arena');
UPDATE `command` SET `help`='Syntax: .modify aspeed #rate\r\n\r\nModifiziert alle Geschwindigkeiten -rennen,schwimmen,rückwärts gehen,rückwärts schwimmen- für den angewählten Spieler auf "Normalgeschwindigkeit für diese Fortbewegenung"*Rate. Falls kein Spieler angewählt ist, wird Euere Geschwindigkeit modifiziert.\r\n\r\n #rate kann von 0.1 bis 10 reichen.' WHERE (`name`='modify aspeed');
UPDATE `command` SET `help`='Syntax: .modify bit #field #bit\r\n\r\nÄndert das #bit Bit des Feldes #field für den angewählten Spieler. Falls kein Spieler angewählt ist, wird Euer Charakter modifiziert.' WHERE (`name`='modify bit');
UPDATE `command` SET `help`='Syntax: .modify bwalk #rate\r\n\r\nModifiziert die Geschwindigkeit der angewählten Spielers währen er rückwärts geht mach "Normales rückwärts gehen"*rate. Falls kein Spieler angewählt ist, wird Euere Geschwindigkeit modifiziert.\r\n\r\n #rate kann von 0.1 bis 10 reichen.' WHERE (`name`='modify bwalk');
UPDATE `command` SET `help`='Syntax: .modify drunk #value\r\n Setzt den Betrunkenheitszustand auf #value (0..100). Der Wert 0 entfernt die Betrunkenheit, 100 ist der höchsten Betrunkenheitszustand.' WHERE (`name`='modify drunk');
UPDATE `command` SET `help`='Syntax: .modify energy #energy\r\n\r\nModifiziert die Energie des angewählten Spielers. Falls kein Spieler angewählt ist, wird Eure Energie modifiziert.' WHERE (`name`='modify energy');
UPDATE `command` SET `help`='Syntax: .modify faction #factionid #flagid #npcflagid #dynamicflagid\r\n\r\nModifiziert die Fraktion und Flagge der angewählten Kreatur. Ohne Argumente wird die Fraktion und Flagge der angewählten Kreatur angezeigt.' WHERE (`name`='modify faction');
UPDATE `command` SET `help`='Syntax: .modify gender male/female\r\n\r\nÄndert das Geschlecht des angewählten Spielers.' WHERE (`name`='modify gender');
UPDATE `command` SET `help`='Syntax: .modify honor $amount\r\n\r\nFügt die Anzahl $amount an Ehrenpunkten dem angewählten Spieler hinzu.' WHERE (`name`='modify honor');
UPDATE `command` SET `help`='Syntax: .modify hp #newhp\r\n\r\nModifiziert die HP des angewählten Spielers. Falls kein Spieler angewählt ist, werden Eure HP modifiziert.' WHERE (`name`='modify hp');
UPDATE `command` SET `help`='Syntax: .modify mana #newmana\r\n\r\nModifiziert die Mana des angewählten Spielers. Falls kein Spieler angewählt ist, wir Euer Mana modifiziert.' WHERE (`name`='modify mana');
UPDATE `command` SET `help`='Syntax: .modify money #money\r\n.money #money\r\n\r\nFügt dem angewählten Spieler Geld hinzu oder nimmt ihm dieses Geld. Falls kein Spieler angewählt ist, wird Euer Geld modifiziert.\r\n\r\n #gold kann negative sein, um Geld wegzunehmen.' WHERE (`name`='modify money');
UPDATE `command` SET `help`='Syntax: .modify morph #displayid\r\n\r\nÄndert Euer derzeitiges Aussehen zu #displayid.' WHERE (`name`='modify morph');
UPDATE `command` SET `help`='Syntax: .modify mount #id #speed\r\n\r\nZeigt den angewählten Spieler als aufgemounted auf die Kreatur mit #id an und setzt die Geschwindigkeit auf den Wert #speed.' WHERE (`name`='modify mount');
UPDATE `command` SET `help`='Syntax: .modify phase #phasemask\r\n\r\nDie Phasemask des ausgewählten Spieler wird auf #phasemask geändert zusammen mit einem Update für die dazugehörende Weltansicht. Die Änderung bleibt aktiv bis die Phase im Spiel sich ändert, oder der GM-mode aktiviert/deaktiviert wird, oder ein Re-Login stattfindet. Die Phasemask des Begleiters des Charakters werden mit dem selben Wert aktualisiert.' WHERE (`name`='modify phase');
UPDATE `command` SET `help`='Syntax: .modify rage #newrage\r\n\r\nModifiziert die Wut (range) des angewählten Spielers. Falls kein Spieler angewählt ist, wir eure Wut modifiziert.' WHERE (`name`='modify rage');
UPDATE `command` SET `help`='Syntax: .modify rep #repId (#repvalue | $rankname [#delta])\r\nSetzt dem gewählten Spieler Ruf bei der Fraktionn #repId auf #repvalue oder auf $reprank.\r\nWenn $reprank angegeben wurde, wird der entstehende Ruf der niedrigste Ruf für diesen Rang plus den Deltabetrag sein, falls angegeben.\r\nDu kannst ''.pinfo rep'' verwenden, um alle bekannten ids aufzulisten oder verwende ''.lookup faction $name'' um eine bestimmte faction id ausfindig zu machen.' WHERE (`name`='modify rep');
UPDATE `command` SET `help`='Syntax: .modify runicpower #newrunicpower\r\n\r\nModifiziert die Runenmacht des angewählten Spielers. Falls kein Spieler angewählt wurde, wird Eure Runenmacht modifiziert.' WHERE (`name`='modify runicpower');
UPDATE `command` SET `help`='Syntax: .modify scale #size\r\n\r\nModifiziert die Größe eines angewählten Spielers. Falls kein Spieler angewählt ist, wird Eure Größe modifiziert.\r\n\r\n #size kann von 0.1 bis 3 reichen.' WHERE (`name`='modify scale');
UPDATE `command` SET `help`='Syntax: .modify speed #rate\r\n.speed #rate\r\n\r\nModifiziert die Geschwindigkeit bei Laufen eines angewählten Spielers nach "Normalgeschwindigkeit"*rate. falls kein Spieler angewählt ist, wird Eure Geschwindigkeit modifiziert.\r\n\r\n #rate kann von 0.1 bis 10 reichen.' WHERE (`name`='modify speed');
UPDATE `command` SET `help`='Syntax: .modify spell\r\n\r\nModifiziert einen Zauber (Spell) des angewählten Spielers. Falls kein Spieler angewählt ist, wird ein Zauber Eures Charakters modifiziert.' WHERE (`name`='modify spell');
UPDATE `command` SET `help`='Syntax: .modify swim #rate\r\n\r\nModifiziert die Schwimmgeschwindigkeit des angewählten Spielers nach "Normale Schwimmgeschiwndigkeit"*rate. Falls kein Spieler angewählt ist, wir Eure Geschwindigkeit modifiziert.\r\n\r\n #rate kann von 0.1 bis 10 reichen.' WHERE (`name`='modify swim');
UPDATE `command` SET `help`='Syntax: .modify titles #mask\n.titles #mask\n\nErlaubt die Benutzung aller Titel von #mask zu benutzen.\n\n #mask=0 deaktiviert das Titel-Wählen-Feld.' WHERE (`name`='modify titles');
UPDATE `command` SET `help`='Syntax: .movegens\r\n  Zeigt eine Liste der Bewegungsgeneratoren für die angewählte Kreatur oder den angewählten Spieler an.' WHERE (`name`='movegens');
UPDATE `command` SET `help`='Syntax: .mute $playerName $timeInMinutes\r\n\r\nDeaktiviert die Chatnachrichten für jeden Charakter des Accounts des Charakters $playerName für $timeInMinutes Minuten.' WHERE (`name`='mute');
UPDATE `command` SET `help`='Syntax: .namego $charactername\r\n\r\nTeleportiert den Zielcharakter zu Euch.' WHERE (`name`='namego');
UPDATE `command` SET `help`='Syntax: .neargrave [alliance|horde]\r\n\r\nFindet den nächsten Friedhof der zur derzeitigen Zone verbunden ist (oder nur den nächsten der Allianz- oder Hordegeister annimmt).' WHERE (`name`='neargrave');
UPDATE `command` SET `help`='Syntax: .notify $MessageToBroadcast\r\n\r\nSendet eine Systemnachticht an alle Spieler, die online sind, auf den Bildschirm.' WHERE (`name`='notify');
UPDATE `command` SET `help`='Syntax: .npc add #creatureid\r\n\r\nSpawnt eine Kreatur mit der gegebenen template id von #creatureid.' WHERE (`name`='npc add');
UPDATE `command` SET `help`='Syntax: .npc additem #itemId <#maxcount><#incrtime><#extendedcost>r\r\n\r\nFügt das Item #itemid zur Verkaufsliste des angewählten Verkäufers hinzu. Ebenso kann optional die maximale Anzahl der Items, die verkauft werden können, die Zeit bis diese wieder aufgefüllt werden und erweiterte Kosten (ExtendedCost) angegeben werden.' WHERE (`name`='npc additem');
UPDATE `command` SET `help`='Noch nicht hinzugefügt.' WHERE (`name`='npc addweapon');
UPDATE `command` SET `help`='Syntax: .npc allowmove\r\n\r\nAktiviert oder deaktiviert die Bewegung für die ausgewählte Kreatur.' WHERE (`name`='npc allowmove');
UPDATE `command` SET `help`='Syntax: .npc changelevel #level\r\n\r\nSetzt das Level der angewählten Kreatur auf #level.\r\n\r\n#level hat einen gültigen Wert von 1 bis 63.' WHERE (`name`='npc changelevel');
UPDATE `command` SET `help`='Syntax: .npc delete [#guid]\r\n\r\nLöscht die Kreatur mit dem Guid #guid (oder die angewählte, falls kein Guid angegeben wurde)' WHERE (`name`='npc delete');
UPDATE `command` SET `help`='Syntax: .npc delitem #itemId\r\n\r\nEntfernt das Item #itemid von der Liste des angewählten Verkäufers.' WHERE (`name`='npc delitem');
UPDATE `command` SET `help`='Syntax: .npc factionid #factionid\r\n\r\nSetzt die Fraktion der ausgewählten Kreatur auf #factionid.' WHERE (`name`='npc factionid');
UPDATE `command` SET `help`='Syntax: .npc flag #npcflag\r\n\r\nSetzt die NPC-Flagge von creature_template der angewählten Kreatur und die der angewählten Kreatur auf #npcflag. Die NPC-Flagge wird auf alle Kreaturen der gewählten creature_template erst nach einem Server Neustart oder einem grid unload/load wirksam.' WHERE (`name`='npc flag');
UPDATE `command` SET `help`='Syntax: .npc follow\r\n\r\nAngwählte Kreatur beginnt Euch zu folgen bis zum Tod/Kampf/etc.' WHERE (`name`='npc follow');
UPDATE `command` SET `help`='Syntax: .npc info\r\n\r\nZeigt eine Liste von Details von der angewählten Kreatur.\r\n\r\nDie Liste beinhaltet:\r\n- GUID, Fraktion, NPC Flagge, Entry ID, Model ID,\r\n- Level,\r\n- Leben (aktuell/maximum),\r\n\r\n- Field flags, dynamic flags, faction tempalte, \r\n- Positionsinformationen,\r\n- und den Kreaturentyp, z.b. falls die Kreatur ein Verkäufer ist.' WHERE (`name`='npc info');
UPDATE `command` SET `help`='Syntax: .npc move [#creature_guid]\r\n\r\nBewegt den Spawnpunkt der derzeitig angewählten Kreatur zu Euren Koordinaten.' WHERE (`name`='npc move');
UPDATE `command` SET `help`='Syntax: .npc name $name\r\n\r\nVerändert den Namen der angewählten Kreatur oder des Charakters zu $name.\r\n\r\nBefehl wurde deaktiviert.' WHERE (`name`='npc name');
UPDATE `command` SET `help`='Syntax: .npc phase #phasemask\r\n\r\nDie Phasemask des angewählten Einheit oder des angewählten Haustiers wird auf #phasemask geändert zusammen mit einem Update für die dazugehörende Weltansicht für die Spieler. Bei einer Kreatur wird der Status in der DB gespeichert und ist dauerhaft. Bei einem Haustier bleibt die Änderung aktiv bis die Phase im Spiel sich für den Besitzer ändert, oder der Besitzer einen Re-Login vornimmt, oder der GM-mode aktiviert/deaktiviert wird.' WHERE (`name`='npc phase');
UPDATE `command` SET `help`='Syntax: .npc playemote #emoteid\r\n\r\nLässt die ausgewählte Kreatur ein Emote ausführen mit einem Emote der ID #emoteid.' WHERE (`name`='npc playemote');
UPDATE `command` SET `help`='Syntax: .npc setdeathstate on/off\r\n\r\nLegt den Standardwert für den Zustand (tot/lebend) eines NPCs beim Spawnen fest.' WHERE (`name`='npc setdeathstate');
UPDATE `command` SET `help`='Syntax: .npc setmodel #displayid\r\n\r\nÄndere das Aussehen der ausgewählten Kreatur auf #displayid.' WHERE (`name`='npc setmodel');
UPDATE `command` SET `help`='Syntax: .npc setmovetype [#creature_guid] stay/random/way [NODEL]\r\n\r\nSetzt für die durch #creature_guid festgelegte Kreatur (oder für die angewählte, falls #creature_guid nicht angegebene wurde) den Bewegungstyp fest und setzt sie auf ihre Respawnpostion zurück (falls die Kreatur lebt). Alle existierenden Waypoints für diese Kreatur werden aus der Datenbank gelöscht, falls nicht NODEL benutzt wurde. Falls die Kreatur tot ist, wird der Bewegungstyp mit dem Kreaturrespawn aktiv.\r\nVergesse keinesfalls NODEL, falls Ihr die Waypoints behalten möchtet.' WHERE (`name`='npc setmovetype');
UPDATE `command` SET `help`='Syntax: .npc spawndist #dist\r\n\r\nÄndert die Spawndistanz der angewählten Kreatur auf #dist.' WHERE (`name`='npc spawndist');
UPDATE `command` SET `help`='Syntax: .npc spawntime #time \r\n\r\nÄndert die Respawnzeit der angewählten Kreatur auf #time.' WHERE (`name`='npc spawntime');
UPDATE `command` SET `help`='Syntax: .npc subname $Name\r\n\r\nÄndert den Zweitnamen(subname) der angewählten Kreatur oder des angewählten Spielers auf $Name.\r\n\r\nBefehl ist deaktiviert.' WHERE (`name`='npc subname');
UPDATE `command` SET `help`='Syntax: .npc tame\r\n\r\nZähmt die angewählte Kreatur (zähmbare nicht Begleiter Kreatur). Ihr müsst keinen Begleiter haben.' WHERE (`name`='npc tame');
UPDATE `command` SET `help`='Syntax: .npc textemote #emoteid\r\n\r\nLässt die angewählte Kreatur den Textemote mit dem Emote mit der ID #emoteid ausführen.' WHERE (`name`='npc textemote');
UPDATE `command` SET `help`='Syntax: .npc unfollow\r\n\r\nAngewählte Kreatur (nicht Begleiter) hört auf Euch zu folgen.' WHERE (`name`='npc unfollow');
UPDATE `command` SET `help`='Syntax: .npc whisper #playerguid #text\r\nDer angewählten NPC flüstert den Text #text dem Spieler #playerguid.' WHERE (`name`='npc whisper');
UPDATE `command` SET `help`='Syntax: .password $old_password $new_password $new_password\r\n\r\nÄndert Euer Account Passwort.' WHERE (`name`='password');
UPDATE `command` SET `help`='Syntax: .pdump write $filename $playerNameOrGUID\r\nSchreibe Charakter dump mit Name/guid $playerNameOrGUID in eine Datei mit dem Namene $filename.' WHERE (`name`='pdump write');
UPDATE `command` SET `help`='Syntax: .pdump load $filename $account [$newname] [$newguid]\r\nLädt character dump aus in Charakterliste von $account mit gespeichertem oder in $newname angegebenem Namen, mit gespeicherter (oder ersten freien) oder in $newguid angegebener guid.' WHERE (`name`='pdump load');
UPDATE `command` SET `help`='Syntax: .pinfo [$player_name] [rep]\r\n\r\nGibt Accountinformationen für den angewählten Spieler oder den Spieler, der mit $player_name gefunden wurde, aus. Falls der Parameter "rep" angegeben wurde, werden Informationen zum Ruf des Spielers angezeigt.' WHERE (`name`='pinfo');
UPDATE `command` SET `help`='Syntax: .plimit [#num|-1|-2|-3|reset|player|moderator|gamemaster|administrator]\r\n\r\nOhne Zusatz wird die derzeitige Spieleranzahl angezeigt und die Berechtigungsstufe für den Serverlogin, mit Zusatz wird das Spielerlimit ($num > 0) oder die Berechtigungsstufe ($num < 0 oder Berechtigungsname. Mit dem Zusatz `reset` wird das Spielerlimit für den Server auf den in der Config angegebenen Wert gesetzt.' WHERE (`name`='plimit');
UPDATE `command` SET `help`='Syntax: .quest add #quest_id\r\n\r\nFügt dem Charakter in seinen Quest-Log den Quest #quest_id. Quest, die durch Items gestartet werden, können durch diesen Befehl nicht hinzugefügt werden, jedoch wird .additem als Befehl hierfür zur Verfügung gestellt.' WHERE (`name`='quest add');
UPDATE `command` SET `help`='Syntax: .quest complete #questid\r\nMarkiert alle Quests als fertiggestellt für die vom angewählten Spieler aktiven Quests. Nach diesem Befehl kann das Ziel die Quests abgeben und die Belohnung erhalten.' WHERE (`name`='quest complete');
UPDATE `command` SET `help`='Syntax: .quest remove #quest_id\r\n\r\nSetzt den Quest #quest_id auf nicht abgeschlossen und nicht aktiv (und entfernt ihn vom derzeitigen Quest-Log) für den angewählten Spieler.' WHERE (`name`='quest remove');
UPDATE `command` SET `help`='Syntax: .recall [$playername]\r\n\r\nTeleportiert $playername oder den angewählten Spieler zu dem Platz an dem er war bevor der letzte teleport-Befehl gebraucht wurde. Falls kein $playername eingegeben wurde oder kein Spieler angewählt wurde, werdet Ihr teleportiert.' WHERE (`name`='recall');
UPDATE `command` SET `help`='Syntax: .reload config\r\n\r\nLädt die Einstellungen der Config neu (standartmäßig in der mangosd.conf zu finden). Nicht alle Einstellungen können bei einem Reload geändert werden: manche neue Werte werden bis zum Neustart ignoriert, andere Werte können mit Verzögerung geändert werden oder sie werden nur auf neue Objekte/Maps angewendet, andere Werte werden erst bei einem Neustart komplett geändert.' WHERE (`name`='reload config');
UPDATE `command` SET `help`='Syntax: .reload all\r\n\r\nLädt alle tables neu, die reload support haben und _safe_(sicher) reloaded werden können.' WHERE (`name`='reload all');
UPDATE `command` SET `help`='Syntax: .reload all_area\r\n\r\nLädt alle `areatrigger_*` tables, die reload support haben und die  _safe_(sicher) reloaded werden können.' WHERE (`name`='reload all_area');
UPDATE `command` SET `help`='Syntax: .reload all_locales\r\n\r\nLädt alle `locales_*` Tabellen neu. Dies wird jetzt supported, sie können also _sicher_ neu geladen werden.' WHERE (`name`='reload all_locales');
UPDATE `command` SET `help`='Syntax: .reload all_loot\r\n\r\nLädt alle `*_loot_template` tables. Dies kann ein langsamer Vorgang werden, der Lags auf dem Server auslöst.' WHERE (`name`='reload all_loot');
UPDATE `command` SET `help`='Syntax: .reload all_quest\r\n\r\nLädt alle tables neu, die mit Quests zusammenhängen und die reload support haben und die  _safe_(sicher) reloaded werden können.' WHERE (`name`='reload all_quest');
UPDATE `command` SET `help`='Syntax: .reload all\r\n\r\nLädt alle `spell_*` tables, die reload support haben und die  _safe_(sicher) reloaded werden können.' WHERE (`name`='reload all_spell');
UPDATE `command` SET `help`='Syntax: .repairitems\r\n\r\nRepariert die Gegenstände aller angewählten Spieler.' WHERE (`name`='repairitems');
UPDATE `command` SET `help`='Syntax: .reset achievements [$playername]\r\n\r\nSetzt die Erfolge des ausgewählten oder benannten (online oder offline) Charakters zurück. Erfolge mit fortdauerndem Prozess wie Quest/etc werden nach dem Reset erneut gefüllt. Erfolge für Events wie Getötete/Zauber/etc gehen verlohren.' WHERE (`name`='reset achievements');
UPDATE `command` SET `help`='Syntax: .reset all spells\r\n\r\nSyntax: .reset all talents\r\n\r\nSetzt die Spells oder Talente beim nächsten Login für alle existierenden Charakter zurück.' WHERE (`name`='reset all');
UPDATE `command` SET `help`='Syntax: .reset honor [Playername]\r\n  Setzt alle Daten, die Ehre betreffen, für den angewählten Charakter zurück (auf 0).' WHERE (`name`='reset honor');
UPDATE `command` SET `help`='Syntax: .reset level [Playername]\r\n  Setzt das Level auf 1 zurück, dies beinhaltet ebenfalls die Stats und Talente.  Angelegte Items mit höherem Level können verloren gehen.' WHERE (`name`='reset level');
UPDATE `command` SET `help`='Syntax: .reset spells [Playername]\r\n  Entfernt alle nicht-originalen Spells (Zauber) vom Zauberbuch. [Playername] kann auch ein Name eines Charakters sein, der offline ist.\r\n.' WHERE (`name`='reset spells');
UPDATE `command` SET `help`='Syntax: .reset stats [Playername]\r\n  Setzt(berechnet neu) alle Stats des angewählten Spielers zu seinen originale Werten des derzeitigen Levels.' WHERE (`name`='reset stats');
UPDATE `command` SET `help`='Syntax: .reset talents [Playername]\r\n  Entfernt alle Talente des angewählten Spielers. [Playername] kann auch ein Name eines Charakters sein, der offline ist.' WHERE (`name`='reset talents');
UPDATE `command` SET `help`='Syntax: .respawn\r\n\r\nRespawned alle angewählten Kreaturen oder alle nahen Kreaturen (wenn keine angewählt wurden) imd GOs ohne Respawnwartezeit.' WHERE (`name`='respawn');
UPDATE `command` SET `help`='Syntax: .revive\r\n\r\nBelebt den angewählten Spieler wieder. Falls kein Spieler angewählt wurde, werdet Ihr wiederbelebt.' WHERE (`name`='revive');
UPDATE `command` SET `help`='Syntax: .save\r\n\r\nSpeichert Euren Charakter.' WHERE (`name`='save');
UPDATE `command` SET `help`='Syntax: .saveall\r\n\r\nSpeichert alle Charaktere im Spiel.' WHERE (`name`='saveall');
UPDATE `command` SET `help`='Syntax: .sendmail #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSendet eine Mail an einen Spieler. Betreff und der Text der Mail müssen in "" angegeben werden. Falls keine Itemanzahl für die ItemID angegeben wird, so wird ein Wert von 1 angenommen, falls die Anzahl > Max Itemplätze, so werden die Items in einer benötigten Anzahl von Plätze gesendet. Alle Plätze in einer Mail sind auf 12 limitiert.' WHERE (`name`='sendmail');
UPDATE `command` SET `help`='Syntax: .sendmessage $playername $message\r\n\r\nSendet Bildschirmnachricht an Spieler von ADMINISTRATOR.' WHERE (`name`='sendmessage');
UPDATE `command` SET `help`='Syntax: .senditems #playername "#subject" "#text" itemid1[:count1] itemid2[:count2] ... itemidN[:countN]\r\n\r\nSendet eine Nachricht an einen Spieler. Betreff und der Text der Mail müssen in "" angegeben werden. Falls für die ItemID keine Mengenangabe gemacht wird, wird der Wert als 1 angenommen, falls Menge > Max Items, die gestapelt werden können, dann werden die Items in mehreren Stapeln versendet. Es können maximal 12 Staoel pro Mail verschickt werden.' WHERE (`name`='senditems');
UPDATE `command` SET `help`='Syntax: .sendmail #playername "#subject" "#text"\r\n\r\nSendet eine Nachricht an einen Spieler. Betreff und der Text der Mail müssen in "" angegeben werden.' WHERE (`name`='sendmail');
UPDATE `command` SET `help`='Syntax: .sendmoney #playername "#subject" "#text" #money\r\n\r\nSendet Geld an einen Spieler. Betreff und der Text der Mail müssen in "" angegeben werden.' WHERE (`name`='sendmoney');
UPDATE `command` SET `help`='Syntax: .server corpses\r\n\r\nLöst corpses expire check in der Welt aus.' WHERE (`name`='server corpses');
UPDATE `command` SET `help`='Syntax: .server exit\r\n\r\nBeendet mangosd SOFORT. Exit code 0.' WHERE (`name`='server exit');
UPDATE `command` SET `help`='Syntax: .server idleshutdown #delay [#exist_code]\r\n\r\nFährt den Server nach #delay Sekunden herunter, falls keine aktiven Verbindungen bestehen (keine Spieler). Benutze #exist_code oder 0 als Programm exist Code.' WHERE (`name`='server idleshutdown');
UPDATE `command` SET `help`='Syntax: .server idleshutdown cancel\r\n\r\nBeendet den Vorgang des Restartens/Herunterfahrens, falls einer vorhanden.' WHERE (`name`='server idleshutdown cancel');
UPDATE `command` SET `help`='Syntax: .server idlerestart #delay\r\n\r\nStartet den Server nach #delay Sekunden neu, falls keine aktiven Verbindungen bestehen (keine Spieler). Benutze #exist_code oder 2 als Programm exist Code.' WHERE (`name`='server idlerestart');
UPDATE `command` SET `help`='Syntax: .server idlerestart cancel\r\n\r\nBeendet den Vorgang des Restartens/Herunterfahrens, falls einer vorhanden.' WHERE (`name`='server idlerestart cancel');
UPDATE `command` SET `help`='Syntax: .server info\r\n\r\nZeigt die Serverversion und die Anzahl der eingeloggten Spieler an.' WHERE (`name`='server info');
UPDATE `command` SET `help`='Syntax: .server motd\r\n\r\nZeigt die Nachricht des Tages an.' WHERE (`name`='server motd');
UPDATE `command` SET `help`='Syntax: .server restart #delay\r\n\r\nStartet den Server nach #delay Sekunden neu. Benutze #exist_code oder 2 als Programm exist code.' WHERE (`name`='server restart');
UPDATE `command` SET `help`='Syntax: .server restart cancel\r\n\r\nBeendet den Vorgang des Restartens/Herunterfahrens, falls einer vorhanden.' WHERE (`name`='server restart cancel');
UPDATE `command` SET `help`='Syntax: .server set loglevel #level\r\n\r\nSetzt Server Log Level (0 - nur Fehler, 1 - standard, 2 - detailliert, 3 - Debug).' WHERE (`name`='server set loglevel');
UPDATE `command` SET `help`='Syntax: .server set motd $MOTD\r\n\r\nÄndert die Nachricht des Tages.' WHERE (`name`='server set motd');
UPDATE `command` SET `help`='Syntax: .server shutdown #delay [#exist_code]\r\n\r\nFährt den Server nach #delay Sekunden herunter. Benutze #exist_code oder 0 als Programm exist code.' WHERE (`name`='server shutdown');
UPDATE `command` SET `help`='Syntax: .server shutdown cancel\r\n\r\nBeendet den Vorgang des Restartens/Herunterfahrens, falls einer vorhanden.' WHERE (`name`='server shutdown cancel');
UPDATE `command` SET `help`='Syntax: .setskill #skill #level [#max]\r\n\r\nSetzt einen Skill der id #skill mit einem korrekten Skillwert von #level und einem Maximalwert von #max (oder einem ähnlich korrekten Maximalwert falls dieser nicht angegeben ist) für den ausgewählten Charakter. Falls kein Charakter angewählt ist, lernt Ihr den Skill.' WHERE (`name`='setskill');
UPDATE `command` SET `help`='Syntax: .showarea #areaid\r\n\r\nDeckt das Gebiet mit #areaid für den angewählten Charakter auf. Falls kein Charakter angewählt ist, wird dieses Gebiet für Euch aufgedeckt.' WHERE (`name`='showarea');
UPDATE `command` SET `help`='Syntax: .showhonor\r\n\r\nZeigt den derzeitigen Stand Eurer Ehre an.' WHERE (`name`='showhonor');
UPDATE `command` SET `help`='Syntax: .start\r\n\r\nTeleportiert Euch in die Startregion Eures Charakters.' WHERE (`name`='start');
UPDATE `command` SET `help`='Syntax: .taxicheat on/off\r\n\r\nGewährt befristeten Zugriff auf alle Flugrouten oder entfernt diesen vom angewählten Charakter. Falls kein Charakter angewählt ist, werden alle Routen für Euch versteckt oder freigegeben.\r\n\r\nBereits besuchte Flugpunkte sind nach der Zugriffszurücknahme weiterhin zugänglich.' WHERE (`name`='taxicheat');
UPDATE `command` SET `help`='Syntax: .tele $location\n\nTeleportiert den Spieler zu dem angegebenen Gebiet.' WHERE (`name`='tele');
UPDATE `command` SET `help`='Syntax: .tele add $name\r\n\r\nFügt Ihre derzeitige Position zur .tele Befehlsliste mit dem Namen $name hinzu.' WHERE (`name`='tele add');
UPDATE `command` SET `help`='Syntax: .tele del $name\r\n\r\nEntfernt das Gebiet mit dem Namen $name von der .tele Befehlsliste.' WHERE (`name`='tele del');
UPDATE `command` SET `help`='Syntax: .tele group#location\r\n\r\nTeleportiert einen angewählten Spieler und seine Gruppenmitglieder zu einem angegebenen Gebiet.' WHERE (`name`='tele group');
UPDATE `command` SET `help`='Syntax: .tele name #playername #location\r\n\r\nTeleportiert einen Spieler zu dem gegebebenen Gebiet.' WHERE (`name`='tele name');
UPDATE `command` SET `help`='Syntax: .ticket on\r\n        .ticket off\r\n        .ticket #num\r\n        .ticket $character_name\r\n\r\nOn/Off zeigt für GMS ein neues Ticket direkt (oder nicht direkt) an, $character_name zeigt die Tickets für diesen Charakter an, #num zeigt das Ticket mit der Nummer #num.' WHERE (`name`='ticket');
UPDATE `command` SET `help`='Syntax: .unaura #spellid\r\n\r\nEntfernt Aura die vom Spell #spellid hervorgerufen wird von der angewählten Einheit.' WHERE (`name`='unaura');
UPDATE `command` SET `help`='Syntax: .unban account $Name\r\nEntbannt einen Account nach einem bestimmten Muster.' WHERE (`name`='unban account');
UPDATE `command` SET `help`='Syntax: .unban character $Name\r\nEntbannt einen Account mit dem Charakter des angegebenen Musters.' WHERE (`name`='unban character');
UPDATE `command` SET `help`='Syntax: .unban ip $Ip\r\nEntbannt einen Account mit der IP des angegebenen Musters.' WHERE (`name`='unban ip');
UPDATE `command` SET `help`='Syntax: .unlearn #spell [all]\r\n\r\nVerlernt dem angewählten Spieler einen Zauber (spell) #spell. Wenn ''all'' angegeben wird, werden alle Ränge verlernt.' WHERE (`name`='unlearn');
UPDATE `command` SET `help`='Syntax: .unmute $playerName\r\n\r\nGibt die Chatnachrichten für jeden Charakter des Accounts des Charakters $playerName.' WHERE (`name`='unmute');
UPDATE `command` SET `help`='Syntax: .waterwalk on/off\r\n\r\nSetzt den Waterwalk-Status für den angewählten Spieler auf [on/off].' WHERE (`name`='waterwalk');
UPDATE `command` SET `help`='Syntax: .wchange #weathertype #status\r\n\r\nSetzt das derzeitge Wetter auf #weathertype mit einer Intensität von #status.\r\n\r\n#weathertype kann sein 1 für Regen, 2 für Schnee, und 3 für Sand. #status kann von 0 für deaktiviert, und 1 für aktiviert sein.' WHERE (`name`='wchange');
UPDATE `command` SET `help`='Syntax: .whispers on|off\r\n\r\nAktiviert/Deaktiviert der Möglichkeit eines Spielers einen GM anzuflüstern. Standartmäßig werden die Angaben von mangosd.conf verwendet.' WHERE (`name`='whispers');
UPDATE `command` SET `help`='Benutzung des WP Kommandos:\r\nJedes Waypoint-Befehl hat seine eigene Beschreibung!' WHERE (`name`='wp');
UPDATE `command` SET `help`='Syntax: .wp add [#creature_guid oder wählt eine Kreatur an]' WHERE (`name`='wp add');
UPDATE `command` SET `help`='Syntax: .wp import $filename' WHERE (`name`='wp import');
UPDATE `command` SET `help`='Syntax: .wp export [#creature_guid oder wählt eine Kreatur an] $filename' WHERE (`name`='wp export');
UPDATE `command` SET `help`='Syntax: .wp modify [#creature_guid oder wählt eine Kreatur an]\r\nadd - Fügt einen Wegpunkt (waypoint) hinter den angewählte visuellen\r\nWartezeit $time\r\nemote ID\r\nspell ID\r\ntext1| text2| text3| text4| text5 <text>\r\nmodel1 ID\r\nmodel2 ID\r\nmove(bewegt den WP zu der Position des Spielers)\r\ndel (löscht den WP)\r\n\r\nNur ein Parameter pro Befehl!' WHERE (`name`='wp modify');
UPDATE `command` SET `help`='Syntax: .wp show [#creature_guid oder wählt eine Kreatur an]\r\nOn\r\nFirst\r\nLast\r\nOff\r\nInfo\r\n\r\nUm eine Information zu gebrauchen müsst Ihr zuerst show auf "on" setzen und dann einen Visuellen-Wegpunkt auswählen und dann show info!' WHERE (`name`='wp show');

SET NAMES 'latin1';
